# Site Information
title: "ThreatTalk"
description: "A hub for insightful blog posts on products and everything information security."
author: "Justin S.A"
url: "justin-s85.github.io/product-security-blog"
baseurl: "" # Leave blank unless your site is hosted in a subdirectory.

# Theme and Aesthetic Settings
theme: minima
paginate: 5 # Number of posts per page.

# Customization
highlighter: rouge
markdown: kramdown

# Social Links
social_links:
  twitter: "https://twitter.com/yourhandle"
  linkedin: "https://linkedin.com/in/yourprofile"
  github: "https://github.com/yourusername"

# Navigation (Optional)
nav_links:
  - name: "Home"
    url: "/"
  - name: "About"
    url: "/about/"
  - name: "Blog"
    url: "/blog/"
  - name: "Contact"
    url: "/contact/"
