name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master  # Trigger on push to master branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Add this step to install Ruby 3.1
    - name: Set up Ruby (version 3.1 or higher)
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'  # Use Ruby 3.1

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build the site with Jekyll
      run: |
        bundle exec jekyll build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site


    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
